### ISSUE TITLE
Try to understand Github projects

### ISSUE THREAD

**Issue by thisisdano** [18F/visual-design#1]
How might we use Github projects, columns, and Trello functionality in our repo?

**Comment by thisisdano** [comment]
OK — so here's the deal:

- **Projects** are, essentially, rudimentary Trello boards. You can have multiple projects per repo. Here's one I made as a test: https://github.com/18F/visual-design/projects/1
- **Issues** and **pull requests** can be set as project **cards**, but cards can also be standalone **notes** that aren't issues (but could be _converted_ to issues)
- Team members can add and edit the **columns** within a project
- Project cards can be moved, sorted, and rearranged on the project boards, and moved from column to column easily
- You can't comment on **notes**, only on **issues**, so keeping the focus on issues probably makes sense from a communication (and notification) perspective

[github projects blog announcement](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features)
[github projects help](https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/)
[a video introduction to github projects](https://www.youtube.com/watch?v=C6MGKHkNtxU)

**Comment by thisisdano** [comment]
@amberwreed ^^

**Comment by jenniferthibault** [comment]
@amberwreed and I chatted briefly about using epics today (not scheduled, it just came up in our check in). 

I hadn't seen GitHub's projects feature before, but it looks really similar to the Epics feature if you use the [ZenHub](https://www.zenhub.com/) plugin. I think ZenHub is growing across 18F, I know at least the FBI & FEC projects are using it...it's sort of like Trello >> Waffle >> Zenhub, but then GitHub released Projects to mimic taskboard planning natively in app. 

One feature I like about ZenHub that it doesn't seem GH Projects has is the ability to filter tasks within the Project/Epic down by assignee, or sprint. Maybe we'd never hit that volume of issues within a project where it would be helpful though.

Sorry, not a lot of decision making here, just adding research points for comparison.

**Comment by jenniferthibault** [comment]
👋 @thisisdano can this be closed? It seems less like a visual design issue and more of a general workflow issue, and I'm not sure it's tied into any particular way of working for this repo (currently, anyways).

**Comment by thisisdano** [comment]
Sure, if it makes folks' lives easier. idk. I still don't have a great perspective on using Zenhub vs. Github projects — I am inclined to want to use GHP cos it's simpler and not based on a plugin, but it's hard to know. I don't think anyone is using this repo enough yet to form a critical mass of opinion.

**Comment by thisisdano** [comment]
That said, I don't think workflow issues are out of scope for this repo.
