### ISSUE TITLE
Visual design community liason

### ISSUE THREAD

**Issue by amberwreed** [18F/visual-design#13]
How might we be more engaged with the visual design community outside of 18F?
Ideas:
- [ ] Set team expectation for outside 18F events attended/participation
- [ ] Liaison to keep team aware of external visual design events
- [ ] Team meet-up at an event

**Comment by jenniferthibault** [comment]
I'm not quire sure how to retitle this one as a user need.

**Comment by jenniferthibault** [comment]
Not currently relevant, closing.
