### ISSUE TITLE
Sign up to work with GDS UK on International design best practices

### ISSUE THREAD

**Issue by thisisdano** [18F/visual-design#29]
more info here: https://designnotes.blog.gov.uk/2017/02/02/building-an-international-group-of-government-designers/

**Comment by thisisdano** [comment]
from that link: 

The UK was recently named as the world’s leading digital government. But it is far from the only digital government.

The D5 member countries – Estonia, Israel, New Zealand and South Korea, alongside the UK – all have well-developed digital organisations in government. The US has two government digital organisations, while Australia’s Digital Transformation Office was explicitly modelled on GDS.

At GDS we work closely with these organisations. We have an international team that co-ordinates all this work - from collaborating on global standards to welcoming international visitors to Aviation House.

Now is the time for us to extend our international work to design.

There are big design challenges facing governments today, and ones that could and should be tackled at a global scale.

We want to set up an international government design group to bring together government designers from around the world. Working across all areas of design, user research, accessibility and content design.

## Going global

We think there are some common issues that affect all designers working in government, whichever country they might be working in. Issues like:

- growing service design
- scaling co-authored patterns
- recruitment and training of design, user research and content roles
- embedding a culture of accessibility
- learning from all our challenges and successes

We want to bring a group of international government designers together to talk about these issues, and more.

## Building a community

We have lots of experience in the UK government of building a design community.

There are currently more than 500 designers working in the UK government. We communicate regularly through Slack and a Google Group. We also get together to talk about our work, share best practice and discuss some of the common issues we face.

We want to use a similar model to build a global government design community. We’ll work with the GDS international team to make this happen.

We’re currently planning how to do this. If you’re a government designer outside the UK and you’d be interested in finding out more, please let us know by filling out this form and we’ll keep you updated.

**Comment by amberwreed** [comment]
Next steps:
- [x] Apply

**Comment by thisisdano** [comment]
I signed up. 🎉

**Comment by jenniferthibault** [comment]
@thisisdano any next steps or follow up issues you'd like to file? Or ok to close?

**Comment by jenniferthibault** [comment]
No longer an active thread, closing.
