### ISSUE TITLE
Develop 18F design principles (_visual_ design principles?)

### ISSUE THREAD

**Issue by thisisdano** [18F/visual-design#32]
Design principles are useful for team and project alignment.

For example, here are general design principles from gov.uk: https://www.gov.uk/design-principles
Guidance on design principles from 18F:  https://pages.18f.gov/design-principles-guide/

Are there general design principles that we can and should have as an organization?
How do those principles intersect with any of 18F's other stated principles?

18F's code of conduct: https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md

**Comment by thisisdano** [comment]
Are there other kinds of principles/standards we have as an organization?

**Comment by amberwreed** [comment]
Collaborators:
@amberwreed

Next steps:
- [ ] Review visual design principle in the wild
- [ ] Gather ideas for usefulness / objectives of visual design principles in govt

**Comment by amberwreed** [comment]
@thisisdano Here's a link to the mural that we used for the brand principles workshop:
https://app.mural.ly/t/gsa6/m/gsa6/1494608188147/39935034a8b41f3d08ae6544003531816c0c2e55

**Comment by amberwreed** [comment]
https://docs.google.com/document/d/1wVdjXrdA7V7QKuIFh9OxQkYjimh2sEZjmhrVVYGGVCs/edit

**Comment by amberwreed** [comment]
https://github.com/18F/visual-design/wiki/Visual-design-principles-%5Bdraft%5D
