### ISSUE TITLE
Visual asset library

### ISSUE THREAD

**Issue by micahtaylor** [18F/visual-design#33]
A central listing and/or file structure for anyone to find visual assets (logos, icons, colors, fonts, etc...).

Such as this scenario - https://gsa-tts.slack.com/archives/visual-design/p1486134677000277

Similar to https://github.com/18F/visual-design/issues/11 but geared more towards "external" individuals and can possibly drive parts of the slackbot - https://github.com/18F/visual-design/issues/6

**Comment by jenniferthibault** [comment]
Closing outdated issues
