### ISSUE TITLE
Guide for documenting / getting approval for projects

### ISSUE THREAD

**Issue by amberwreed** [18F/visual-design#34]
Here's a template for what should be described before starting a story:

- [ ] Description
- [ ] User needs this meets
- [ ] Team needs this meets
- [ ] Support needed
- [ ] Dependencies
- [ ] Next steps
- [ ] We can close this issue when...
- [ ] Identify collaborators

**Comment by thisisdano** [comment]
## Description
So, what is this all about? Add one or two sentences describing this issue.

## User needs this meets
What specific kinds of users is this issue for? What do they get out of it?

- user need tk
- user need tk

## Team needs this meets
How does this further support the team or organization? [Is this redundant with users above?]

## Support needed
What skills are needed on this issue?

## Dependencies
Anything that needs to happen before working on this issue?

- dependency tk
- dependency tk

## Next steps
What needs to happen to get this issue off the ground?

- step tk
- step tk

## We can close this issue when...
What are the success criteria for this issue? Write these not for you, but for someone who would independently assess success.

- [ ] success criterion tk
- [ ] success criterion tk
- [ ] success criterion tk

## Issue collaborators
Who else do you expect to work with on this project? Add their github handles here. 

- collaborator tk
- collaborator tk

## Administrative use only
- [ ] Approved!

**Comment by thisisdano** [comment]
^^^ I took a stab at a template for this

**Comment by jenniferthibault** [comment]
@thisisdano this is a really awesome template, but my sense is that internal project processes have changed. Would you like to move this template forward to another group or...?

**Comment by jenniferthibault** [comment]
Jen to send to Liz for future use

**Comment by jenniferthibault** [comment]
Moved to the internal project repo, closing
