### ISSUE TITLE
Update google slide template

### ISSUE THREAD

**Issue by amberwreed** [18F/visual-design#44]
- [ ] Review in the visual design huddle

- [ ] Review for accessibility (contrast)

- [ ] Assess need for logo

- [ ] Simplify slides that are common problems for non-designers

- [ ] Do we need to add any new slides? Are people creating things from scratch

- [ ] Add best practices on a master

- [ ] Save a copy when you start for the archives and save over the master

**Comment by jenniferthibault** [comment]
Closing outdated issues
